### ISSUE TITLE
Add IOTEX, SOLO, KDA, GAFI, VEE, CEEK, PBR, KYL

### ISSUE THREAD

**Issue by tifDev** [tifDev/crypto-watchlists#4]
Answer the below questions:

- **Why should we add this coin? What Makes It Unique and perks?**
These coins have a big potential and saw big growth recently.
- **Wich group does this coin belong?** (f.e. privacy coins, smart contracts platform, AMM's, etc...)
[Added to Coins with potential](https://coinmarketcap.com/watchlist/61797777b160446a2545df71)

- **What is the Coinmarketcap coin link?**
- [IOTEX](https://coinmarketcap.com/currencies/sologenic/)
- [SOLOl](https://coinmarketcap.com/currencies/sologenic/)
- [KDA](https://coinmarketcap.com/currencies/kadena/)
- [GAFI](https://coinmarketcap.com/currencies/gamefi/)
- [VEE](https://coinmarketcap.com/currencies/blockv/)
- [CEEK](https://coinmarketcap.com/currencies/ceek-vr/)
- [PBR](https://coinmarketcap.com/currencies/polkabridge/)
- [KYL](https://coinmarketcap.com/currencies/kylin/)

**Comment by tifDev** [comment]
Coins added

**Comment by josuecv26** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
aaa1999, @sindey1982, @emacsenli, @michaelchiche, @Roobae420, @HUGHNew, @why168, @Supsource, @vasvl123, @alona789, @Asinjon, @bnclt, @Yang-J-LIN, @torys877, @alechilczenko, @NayLinHtet4942, @VahidSaadat, @khaidardotco, @naijoug, @binary-sequence, @davey2, @15th, @iewgnaw, @gdf152535, @feynon, @roseMix, @xephysis, @wdd233, @freerafiki, @dacoffey, @shokosanma, @wozhi-cl, @Yananeer, @EugeneKorneev, @indigos33k3r, @nodnarb123, @redlight7, @pwj1568, @willxuecn, @SteveFroehlich, @hunterhawk, @Chiipandaren, @everton-e26, @zamansoum, @abyssimth, @kilient, @foxchys, @Bllss, @sirpappa, @lucayepa
